name: Staging Deployment

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      # - name: gogogo
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: "1.21.1"
      #   run: go version
