name: Staging Deployment

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.1"

      - name: Verify Go installation
        run: go version

      - name: compile Go
        run: |
          cd src
          go build -o bin/main

      - name: Test and run the build application
        run: ./bin/main
